export const USERNAME_DIV_ID = 'username-div'
export const EMAIL_DIV_ID = 'email-div'
export const USER_ASIDE_ID = 'user-asid-div'
export const EMAIL_ASIDE_ID = 'email-aside-id'
export const USER_DIV_ID = 'user-div'
export const PASSWORD_DIV_ID = 'password-div'
export const PASSWORD_ASIDE_ID = 'password-aside-id'
