export const PASSWORD_REQUIRED = 'Password is required'
export const EMAIL_REQUIRED = 'Email is required'
export const USERNAME_REQUIRED = 'Username is required'
export const USER_OR_EMAIL_REQUIRED = 'Username or email is required'
export const USER_NOT_FOUND = 'No user found, please check credentials again'
export const USER_EXISTS = 'User already exists'
export const PASSWORD_REQUIREMENT =
  'Password needs to be at least 8 english characters, with at least 1 upper case, 1 lower case, and 1 number'
export const EMAIL_NOT_VALID = 'Email is not valid'
export const EMAIL_VALIDATOR = '^[\\w-.]+@([\\w-]+.)+[\\w-]{2,4}$'
export const PASSWORD_VALIDATOR = '^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$'
