export const PASSWORD_REQUIRED = 'Password is required'
export const EMAIL_REQUIRED = 'Email is required'
export const USERNAME_REQUIRED = 'Username is required'
export const USER_OR_EMAIL_REQUIRED = 'Username or email is required'
export const USER_NOT_FOUND = 'No user found, please check credentials again'
export const USER_EXISTS = 'User already exists'
